# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 700)
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.labelTitle.setFont(font)
        self.labelTitle.setStyleSheet("color: rgb(68, 84, 106);")
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.frameButtonLoad = QtWidgets.QFrame(self.centralwidget)
        self.frameButtonLoad.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameButtonLoad.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameButtonLoad.setObjectName("frameButtonLoad")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameButtonLoad)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonLoadFile = QtWidgets.QPushButton(self.frameButtonLoad)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.buttonLoadFile.setFont(font)
        self.buttonLoadFile.setStyleSheet("QWidget:enabled {background-color: rgb(68, 84, 106);\n"
"border-color: rgb(68, 84, 106);\n"
"border-width: 3px;\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"padding: 4px;\n"
"color: white;}\n"
"\n"
"QWidget:disabled{background-color: lightgrey;\n"
"border-color: rgb(68, 84, 106);\n"
"border-width: 3px;\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"padding: 4px;\n"
"color: grey;}\n"
"\n"
"\n"
"")
        self.buttonLoadFile.setObjectName("buttonLoadFile")
        self.horizontalLayout.addWidget(self.buttonLoadFile)
        self.verticalLayout.addWidget(self.frameButtonLoad)
        self.frameInsert = QtWidgets.QFrame(self.centralwidget)
        self.frameInsert.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInsert.setObjectName("frameInsert")
        self.horizontalLayoutSettings = QtWidgets.QHBoxLayout(self.frameInsert)
        self.horizontalLayoutSettings.setObjectName("horizontalLayoutSettings")
        self.frameF = QtWidgets.QFrame(self.frameInsert)
        self.frameF.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameF.setObjectName("frameF")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameF)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelF = QtWidgets.QLabel(self.frameF)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        self.labelF.setFont(font)
        self.labelF.setStyleSheet("color: rgb(68, 84, 106);")
        self.labelF.setAlignment(QtCore.Qt.AlignCenter)
        self.labelF.setObjectName("labelF")
        self.verticalLayout_2.addWidget(self.labelF)
        self.lineEditF = QtWidgets.QLineEdit(self.frameF)
        self.lineEditF.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.lineEditF.setFont(font)
        self.lineEditF.setStyleSheet("border-radius: 10px;\n"
"color: rgb(68, 84, 106);")
        self.lineEditF.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditF.setObjectName("lineEditF")
        self.verticalLayout_2.addWidget(self.lineEditF)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 5)
        self.horizontalLayoutSettings.addWidget(self.frameF)
        self.frameD = QtWidgets.QFrame(self.frameInsert)
        self.frameD.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameD.setObjectName("frameD")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frameD)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelD = QtWidgets.QLabel(self.frameD)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        self.labelD.setFont(font)
        self.labelD.setStyleSheet("color: rgb(68, 84, 106);")
        self.labelD.setAlignment(QtCore.Qt.AlignCenter)
        self.labelD.setObjectName("labelD")
        self.verticalLayout_3.addWidget(self.labelD)
        self.lineEditD = QtWidgets.QLineEdit(self.frameD)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.lineEditD.setFont(font)
        self.lineEditD.setStyleSheet("border-radius: 10px;\n"
"color: rgb(68, 84, 106);")
        self.lineEditD.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditD.setObjectName("lineEditD")
        self.verticalLayout_3.addWidget(self.lineEditD)
        self.horizontalLayoutSettings.addWidget(self.frameD)
        self.horizontalLayoutSettings.setStretch(0, 1)
        self.horizontalLayoutSettings.setStretch(1, 1)
        self.verticalLayout.addWidget(self.frameInsert)
        self.frameImagesSpace = QtWidgets.QFrame(self.centralwidget)
        self.frameImagesSpace.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameImagesSpace.setObjectName("frameImagesSpace")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frameImagesSpace)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.frameImagesSpace)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelImageOriginal = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.labelImageOriginal.setFont(font)
        self.labelImageOriginal.setStyleSheet("color: rgb(68, 84, 106);")
        self.labelImageOriginal.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelImageOriginal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelImageOriginal.setLineWidth(5)
        self.labelImageOriginal.setMidLineWidth(0)
        self.labelImageOriginal.setScaledContents(False)
        self.labelImageOriginal.setAlignment(QtCore.Qt.AlignCenter)
        self.labelImageOriginal.setWordWrap(False)
        self.labelImageOriginal.setObjectName("labelImageOriginal")
        self.verticalLayout_4.addWidget(self.labelImageOriginal)
        self.verticalLayout_6.addWidget(self.frame_3, 0, QtCore.Qt.AlignHCenter)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButtonOriginal = QtWidgets.QRadioButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.radioButtonOriginal.setFont(font)
        self.radioButtonOriginal.setStyleSheet("QRadioButton:enabled {\n"
"    color: #44546a; \n"
"}\n"
"\n"
"QRadioButton:disabled{\n"
"color: grey;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 9px;\n"
"    border: 2px solid #44546a;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #44546a;\n"
"    border: 2px solid #44546a;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color: white;\n"
"    border: 2px solid #44546a;\n"
"}\n"
"\n"
"QRadioButton::indicator:disabled {\n"
"    background-color: white;\n"
"    border: 2px solid grey;\n"
"}")
        self.radioButtonOriginal.setChecked(True)
        self.radioButtonOriginal.setObjectName("radioButtonOriginal")
        self.horizontalLayout_4.addWidget(self.radioButtonOriginal)
        self.radioButtonCropped = QtWidgets.QRadioButton(self.frame_2)
        self.radioButtonCropped.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.radioButtonCropped.setFont(font)
        self.radioButtonCropped.setStyleSheet("QRadioButton:enabled {\n"
"    color: #44546a; \n"
"}\n"
"\n"
"QRadioButton:disabled{\n"
"color: grey;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 9px;\n"
"    border: 2px solid #44546a;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #44546a;\n"
"    border: 2px solid #44546a;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color: white;\n"
"    border: 2px solid #44546a;\n"
"}\n"
"\n"
"QRadioButton::indicator:disabled {\n"
"    background-color: white;\n"
"    border: 2px solid grey;\n"
"}")
        self.radioButtonCropped.setObjectName("radioButtonCropped")
        self.horizontalLayout_4.addWidget(self.radioButtonCropped)
        self.radioButtonCroppedWithGrid = QtWidgets.QRadioButton(self.frame_2)
        self.radioButtonCroppedWithGrid.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.radioButtonCroppedWithGrid.setFont(font)
        self.radioButtonCroppedWithGrid.setStyleSheet("QRadioButton:enabled {\n"
"    color: #44546a; \n"
"}\n"
"\n"
"QRadioButton:disabled{\n"
"color: grey;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 9px;\n"
"    border: 2px solid #44546a;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #44546a;\n"
"    border: 2px solid #44546a;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color: white;\n"
"    border: 2px solid #44546a;\n"
"}\n"
"\n"
"QRadioButton::indicator:disabled {\n"
"    background-color: white;\n"
"    border: 2px solid grey;\n"
"}")
        self.radioButtonCroppedWithGrid.setObjectName("radioButtonCroppedWithGrid")
        self.horizontalLayout_4.addWidget(self.radioButtonCroppedWithGrid)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 1)
        self.verticalLayout_6.addWidget(self.frame_2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_6.setStretch(1, 1)
        self.horizontalLayout_3.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter)
        self.frame_4 = QtWidgets.QFrame(self.frameImagesSpace)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelImageTransformed = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.labelImageTransformed.setFont(font)
        self.labelImageTransformed.setStyleSheet("color: rgb(68, 84, 106);")
        self.labelImageTransformed.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelImageTransformed.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelImageTransformed.setLineWidth(5)
        self.labelImageTransformed.setAlignment(QtCore.Qt.AlignCenter)
        self.labelImageTransformed.setObjectName("labelImageTransformed")
        self.verticalLayout_5.addWidget(self.labelImageTransformed)
        self.verticalLayout_7.addWidget(self.frame_5, 0, QtCore.Qt.AlignHCenter)
        self.buttonSave = QtWidgets.QPushButton(self.frame_4)
        self.buttonSave.setEnabled(False)
        self.buttonSave.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.buttonSave.setFont(font)
        self.buttonSave.setStyleSheet("QWidget:enabled {background-color: rgb(68, 84, 106);\n"
"border-color: rgb(68, 84, 106);\n"
"border-width: 3px;\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"padding: 4px;\n"
"color: white;}\n"
"\n"
"QWidget:disabled{background-color: lightgrey;\n"
"border-color: rgb(68, 84, 106);\n"
"border-width: 3px;\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"padding: 4px;\n"
"color: grey;}\n"
"\n"
"\n"
"")
        self.buttonSave.setObjectName("buttonSave")
        self.verticalLayout_7.addWidget(self.buttonSave)
        self.verticalLayout_7.setStretch(1, 1)
        self.horizontalLayout_3.addWidget(self.frame_4, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frameImagesSpace)
        self.frameButtonStart = QtWidgets.QFrame(self.centralwidget)
        self.frameButtonStart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameButtonStart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameButtonStart.setObjectName("frameButtonStart")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameButtonStart)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonPreview = QtWidgets.QPushButton(self.frameButtonStart)
        self.buttonPreview.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.buttonPreview.setFont(font)
        self.buttonPreview.setStyleSheet("QWidget:enabled {background-color: rgb(68, 84, 106);\n"
"border-color: rgb(68, 84, 106);\n"
"border-width: 3px;\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"padding: 4px;\n"
"color: white;}\n"
"\n"
"QWidget:disabled{background-color: lightgrey;\n"
"border-color: rgb(68, 84, 106);\n"
"border-width: 3px;\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"padding: 4px;\n"
"color: grey;}\n"
"\n"
"\n"
"")
        self.buttonPreview.setObjectName("buttonPreview")
        self.horizontalLayout_2.addWidget(self.buttonPreview)
        self.buttonStart = QtWidgets.QPushButton(self.frameButtonStart)
        self.buttonStart.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.buttonStart.setFont(font)
        self.buttonStart.setStyleSheet("QWidget:enabled {background-color: rgb(68, 84, 106);\n"
"border-color: rgb(68, 84, 106);\n"
"border-width: 3px;\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"padding: 4px;\n"
"color: white;}\n"
"\n"
"QWidget:disabled{background-color: lightgrey;\n"
"border-color: rgb(68, 84, 106);\n"
"border-width: 3px;\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"padding: 4px;\n"
"color: grey;}\n"
"\n"
"\n"
"")
        self.buttonStart.setObjectName("buttonStart")
        self.horizontalLayout_2.addWidget(self.buttonStart)
        self.verticalLayout.addWidget(self.frameButtonStart)
        self.frameStatus = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.frameStatus.setFont(font)
        self.frameStatus.setStyleSheet("color: rgb(68, 84, 106);")
        self.frameStatus.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameStatus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameStatus.setObjectName("frameStatus")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frameStatus)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.labelStatus = QtWidgets.QLabel(self.frameStatus)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.labelStatus.setFont(font)
        self.labelStatus.setText("")
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout_8.addWidget(self.labelStatus)
        self.verticalLayout.addWidget(self.frameStatus, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 10)
        self.verticalLayout.setStretch(4, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DCT2 Converter"))
        self.labelTitle.setText(_translate("MainWindow", "DCT2 Converter - RGB & Grayscale"))
        self.buttonLoadFile.setText(_translate("MainWindow", "Load Image"))
        self.labelF.setText(_translate("MainWindow", "Insert F"))
        self.lineEditF.setText(_translate("MainWindow", "8"))
        self.labelD.setText(_translate("MainWindow", "Insert d"))
        self.lineEditD.setText(_translate("MainWindow", "10"))
        self.labelImageOriginal.setText(_translate("MainWindow", "Original Image"))
        self.radioButtonOriginal.setText(_translate("MainWindow", "Original"))
        self.radioButtonCropped.setText(_translate("MainWindow", "Cropped"))
        self.radioButtonCroppedWithGrid.setText(_translate("MainWindow", "Grid"))
        self.labelImageTransformed.setText(_translate("MainWindow", "Transformed Image"))
        self.buttonSave.setText(_translate("MainWindow", "Save"))
        self.buttonPreview.setText(_translate("MainWindow", "Prepare"))
        self.buttonStart.setText(_translate("MainWindow", "Start"))
